[input]

# starting letters for name generator
namePrefix = ma

# count of names to generate
genCount = 7

#######################################

[model]

# name generator model's path
modelPath = ./models/nameGenModel.pth

# model tolerance value- higher value => name generator softens 
modelTolerance = 3.0

